load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "oci_runtime",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    edition = "2024",
    visibility = ["//lib:__subpackages__"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "oci_runtime_test",
    crate = ":oci_runtime",
    timeout = "short",
)
