load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load(":toolchains.bzl", "current_launcher")

package(default_visibility = ["//visibility:private"])

# The launcher for the execution platform, used as the layer indexer in
# `runc_binary` build actions.
current_launcher(name = "current_launcher")

bzl_library(
    name = "runc_binary",
    srcs = ["runc_binary.bzl"],
    visibility = [
        "//docs:__subpackages__",
        "//lib:__subpackages__",
    ],
    deps = [":toolchains"],
)

bzl_library(
    name = "toolchains",
    srcs = ["toolchains.bzl"],
    visibility = [
        "//docs:__subpackages__",
        "//lib:__subpackages__",
    ],
)
