"""Prebuilt launcher release pinned by the `launcher` module extension.

Regenerated by `.github/workflows/make_release_archive.sh` when a release
archive is built. Empty hashes mark an unreleased checkout, where no prebuilt
launcher exists to download.
"""

visibility(["//lib/..."])

LAUNCHER_VERSION = "0.0.0"

LAUNCHER_SHA256 = {
    "linux_amd64": "",
    "linux_arm64": "",
}
